[100 道 numpy 练习](https://zhuanlan.zhihu.com/p/58576235)

# 导入numpy

In [1]:
import numpy as np

# 打印版本和配置说明

In [3]:
np.__version__

'1.19.2'

In [2]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']


创建一个长度为10的空间向量

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

一个数组的内存大小

In [9]:
Z=np.zeros((10,10))
print("%d bytes"%(Z.size*Z.itemsize))

800 bytes


从命令行得到numpy中add函数的说明文档

In [13]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

 创建一个长度为 10 并且除了第五个值为 1 的空向量

In [16]:
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
创建一个值域范围从 10 到 49 的向量

In [17]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
反转一个向量 (第一个元素变为最后一个)

In [19]:
Z=np.arange(50)
Z=Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [ ]:
创建一个 3x3 并且值从 0 到 8 的矩阵

In [21]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
找到数组 [1,2,0,0,4,0] 中非 0 元素的位置索引

In [24]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [ ]:
创建一个 3x3 的单位矩阵

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
创建一个 3x3x3 的随机数组

In [26]:
np.random.random((3,3,3))

array([[[0.62941444, 0.50378687, 0.25454731],
        [0.65701899, 0.20964533, 0.66543224],
        [0.82617438, 0.14844942, 0.6223741 ]],

       [[0.46125628, 0.08849269, 0.278632  ],
        [0.17712264, 0.26785489, 0.45400291],
        [0.55005873, 0.52808551, 0.59823446]],

       [[0.43802084, 0.96346168, 0.55764984],
        [0.44473162, 0.72649593, 0.48629914],
        [0.12642186, 0.41110032, 0.82292527]]])

In [33]:
np.random.random((3,3))

array([[0.80750177, 0.14411208, 0.34071695],
       [0.98000825, 0.87089461, 0.52432803],
       [0.99138268, 0.53464353, 0.68001942]])

In [ ]:
创建一个 10x10 的随机数组并找到它的最大值和最小值

In [35]:
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()
print(Zmin,Zmax)

0.019296004470018224 0.9918281336301414


In [ ]:
创建一个长度为 30 的随机向量并找到它的平均值

In [36]:
Z=np.random.random(30)
m=Z.mean()
print(m)

0.5244919538915774


In [ ]:
创建一二维数组，其中边界值为 1，其余值为 0

In [37]:
Z=np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
对于一个存在在数组，如何添加一个用 0 填充的边界？

In [39]:
Z = np.ones((5,5))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
以下表达式运行的结果分别是什么
NaN = not a number, inf = infinity

In [40]:
0*np.nan

nan

In [41]:
np.nan==np.nan

False

In [44]:
np.inf>np.nan

False

In [45]:
np.nan-np.nan

nan

In [46]:
0.3==3*0.1

False

In [ ]:
创建一个 5x5 的矩阵，并设置值 1,2,3,4 落在其对角线下方位置

In [47]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [48]:
np.diag(np.arange(4))

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [53]:
np.diag(np.arange(3),k=-1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0]])

In [ ]:
创建一个 8x8 的矩阵，并且设置成棋盘样式

In [54]:
Z=np.zeros((8,8),dtype=int)

In [56]:
Z[1::2,::2]=1

In [58]:
Z[::2,1::2]=1

In [59]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
考虑一个 (6,7,8) 形状的数组，其第 100 个元素的索引 (x,y,z) 是什么？

In [60]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [ ]:
用 tile 函数去创建一个 8x8 的棋盘样式矩阵

In [61]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
对一个 5x5 的随机矩阵做归一化

In [63]:
Z=np.random.random((5,5))
Zmax,Zmin=Z.max(),Z.min()
Z=(Z-Zmin)/(Zmax-Zmin)
print(Z)

[[1.         0.36227668 0.47380576 0.67769108 0.06189304]
 [0.92343675 0.86073344 0.31772376 0.49279082 0.43131108]
 [0.60319139 0.01363965 0.76274011 0.07779754 0.23557616]
 [0.13103286 0.76077508 0.07887937 0.21608414 0.22632863]
 [0.54258964 0.         0.64087817 0.87116663 0.84248293]]


In [ ]:
 创建一个将颜色描述为 (RGBA) 四个无符号字节的自定义 dtype？

In [65]:
color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
color

<ipython-input-65-d386a2bbd3b1>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [ ]:
一个 5x3 的矩阵与一个 3x2 的矩阵相乘，实矩阵乘积是什么？

In [66]:
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
给定一个一维数组，对其在 3 到 8 之间的所有元素取反

In [68]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
下面脚本运行后的结果是什么？

In [69]:
sum(range(5),-1)

9

In [70]:
np.sum(range(5),-1)

10

In [ ]:
27. 考虑一个整数向量 Z, 下列表达合法的是哪个？